// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_ImageLight1 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_ImageLight2 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_ImageLight4 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_ImageLight3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Image55 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImageLight1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        LEDcontorl(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImageLight2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        LEDcontorl(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImageLight3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);

        LEDcontorl(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ImageLight4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        LEDcontorl(e);
    }
}

void ui_event_Image55(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image13, &ui_img_background_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 132
    lv_obj_set_x(ui_Image13, 26);
    lv_obj_set_y(ui_Image13, -6);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image13, 990);

    ui_Image6 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image6, &ui_img_557891352);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image6, -217);
    lv_obj_set_y(ui_Image6, -41);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 150);

    ui_ImageLight1 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ImageLight1, &ui_img_463845234);
    lv_obj_set_width(ui_ImageLight1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_ImageLight1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_ImageLight1, -217);
    lv_obj_set_y(ui_ImageLight1, -41);
    lv_obj_set_align(ui_ImageLight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageLight1, 150);

    ui_Image7 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image7, &ui_img_557891352);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image7, -67);
    lv_obj_set_y(ui_Image7, -43);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 150);

    ui_ImageLight2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ImageLight2, &ui_img_463845234);
    lv_obj_set_width(ui_ImageLight2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_ImageLight2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_ImageLight2, -66);
    lv_obj_set_y(ui_ImageLight2, -42);
    lv_obj_set_align(ui_ImageLight2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageLight2, 150);

    ui_Image10 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image10, &ui_img_557891352);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image10, 239);
    lv_obj_set_y(ui_Image10, -37);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 150);

    ui_ImageLight4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ImageLight4, &ui_img_463845234);
    lv_obj_set_width(ui_ImageLight4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_ImageLight4, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_ImageLight4, 238);
    lv_obj_set_y(ui_ImageLight4, -37);
    lv_obj_set_align(ui_ImageLight4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageLight4, 150);

    ui_Image12 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image12, &ui_img_557891352);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image12, 89);
    lv_obj_set_y(ui_Image12, -38);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 150);

    ui_ImageLight3 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_ImageLight3, &ui_img_463845234);
    lv_obj_set_width(ui_ImageLight3, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_ImageLight3, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_ImageLight3, 90);
    lv_obj_set_y(ui_ImageLight3, -39);
    lv_obj_set_align(ui_ImageLight3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageLight3, 150);

    ui_Label4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -213);
    lv_obj_set_y(ui_Label4, 51);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "客厅");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 87);
    lv_obj_set_y(ui_Label5, 52);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "卧室");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 240);
    lv_obj_set_y(ui_Label6, 53);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "厨房");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -65);
    lv_obj_set_y(ui_Label7, 49);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "书房");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_TextFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button3, 83);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -217);
    lv_obj_set_y(ui_Button3, 113);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "开关灯");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_TextFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button4, 89);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -67);
    lv_obj_set_y(ui_Button4, 111);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "开关灯");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_TextFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 94);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 95);
    lv_obj_set_y(ui_Button5, 111);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "开关灯");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_TextFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 248);
    lv_obj_set_y(ui_Button6, 111);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "开关灯");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_TextFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image55 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image55, &ui_img_1609717271);
    lv_obj_set_width(ui_Image55, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image55, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image55, -363);
    lv_obj_set_y(ui_Image55, -208);
    lv_obj_set_align(ui_Image55, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image55, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image55, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image55, ui_event_Image55, LV_EVENT_ALL, NULL);

    LightMQTTcontrl();
}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image13 = NULL;
    ui_Image6 = NULL;
    ui_ImageLight1 = NULL;
    ui_Image7 = NULL;
    ui_ImageLight2 = NULL;
    ui_Image10 = NULL;
    ui_ImageLight4 = NULL;
    ui_Image12 = NULL;
    ui_ImageLight3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Button3 = NULL;
    ui_Label31 = NULL;
    ui_Button4 = NULL;
    ui_Label33 = NULL;
    ui_Button5 = NULL;
    ui_Label34 = NULL;
    ui_Button6 = NULL;
    ui_Label35 = NULL;
    ui_Image55 = NULL;

}
